trigger:
  batch: false
  branches:
    include:
    - master
    - azure-pipelines
    - release-*

# describe each job seperately
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15'
  - bash: ./scripts/azure-electron-build.sh
    env:
      GH_TOKEN: $(github_token)

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  # Install an Apple certificate required to build on a macOS agent
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: mac.p12
      certPwd: $(macP12Pass)
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15'
  - bash: ./scripts/azure-electron-build.sh
    env:
      GH_TOKEN: $(github_token)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15'
  - bash: ./scripts/azure-electron-build.sh
    env:
      GH_TOKEN: $(github_token)
      WIN_CSC_KEY_PASSWORD: $(csc_key_password)
      WIN_CSC_LINK: $(csc_link)
