# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# according to this, below should work
# https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops
#strategy:
#  matrix:
#    linux:
#      imageName: 'ubuntu-16.04'
#    mac:
#      imageName: 'macos-10.13'
#    windows:
#      imageName: 'vs2017-win2016'
#
#pool:
#  vmImage: $(imageName)
#
#steps:
#- script: echo Hello, $(imageName)

# describe each job seperately
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      ./scripts/azure-electron-build.sh
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: |
      ./scripts/azure-electron-build.sh
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      ./scripts/azure-electron-build.sh

#trigger:
#- master
#- azure-pipelines
#
#jobs:
#  - job: build_augur_app
#    displayName: 'Build Augur App'
#    strategy:
#      matrix:
#        mac:
#          imageName: 'macOS-10.13'
#          build_command: make-mac
#        win:
#          imageName: 'windows-2019'
#          build_command: make-win
#        linux:
#          imageName: 'Ubuntu-16.04'
#          build_command: make-linux
#    pool:
#      vmImage: $(imageName)
#    steps:
#      - task: NodeTool@0
#        inputs:
#          versionSpec: 10.15
#      - script: echo Hello, world!
#        displayName: 'Run a one-line script'
#
#      - bash: |
#          set -euo pipefail
#          echo $(imageName)
#          env
#          npm install
#          NODE_ENV=production npm run $(build_command)
#          cat dist/*.sha256
#        displayName: 'build augur-app'
