# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

jobs:
  - job: build_augur_app
    displayName: 'Build Augur App'
    strategy:
      matrix:
        mac:
          vmimage: macOS-10.13
        win:
          vmimage: windows-2019
        linux:
          vmimage: Ubuntu-16.04
    pool:
      vmImage: $(vmimage)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.15
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
