export const MODAL_EDIT_CONNECTION = "MODAL_EDIT_CONNECTION";
export const MODAL_DELETE_CONNECTION = "MODAL_DELETE_CONNECTION";
export const MODAL_DOWNLOAD_GETH = "MODAL_DOWNLOAD_GETH";
export const MODAL_EDIT_UI_PORT = "MODAL_EDIT_UI_PORT";
